#!/bin/bash

DOTS_DIR="$HOME/dots/"
NAMED=false
STEP=1

for (( i=1; i<=$#; i=$(($i + $STEP)) )); do
    arg=${!i}
    if [[ $arg == '-n' ]]; then
        NAMED=true
        STEP=2
        i=$(($i + 1))
        arg=${!i}
    fi

    file=$arg
    if $NAMEDi; then
        j=$((i + 1))
        link_name=${!j}
    else
        link_name=$(basename $file | cut -d '.' -f2)
    fi

    if [[ -f $file ]]; then
        f_path=$(readlink -f $file | grep -o "/.*/")

        while [[ -e $DOTS_DIR$link_name ]]; do
            echo "File with name $link_name ( $file ) alredy in dots"
            read -p "Rename it: " link_name
        done

        mv $file $DOTS_DIR$link_name
        ln -s $DOTS_DIR$link_name $f_path$f_name

        echo "Added $file as $link_name to dots"
    else
        echo "File $file does not exist"
    fi
done

