#!/bin/bash

read state level time <<< $(acpi | cut -d ' ' -f3,4,5 | tr -d ',')

green="#189C07"
yellow="#F7E017"
red="#E00A0A"
lgreen="#55C90F"

battery='BAT'
charger='CHR'

if [[ $state == "Discharging" ]]; then
    if [[ $level == "100%" ]]; then
        color=$green
    elif [[ $level < "50%" ]]; then
        color=$yellow
    elif [[ $level < "10%" ]]; then
        color=$red
    else
        color=$lgreen
    fi

    icon=$battery
else
    color=$green
    icon=$charger
fi

if [[ $time =~ [0-9]*[0-9]:..:.. ]]; then
    time=" [$time]"
else
    time=""
fi

echo "$icon $level$time"
echo ""
echo "$color"

