#!/bin/bash

BRIGHTNESS_PATH="/sys/class/backlight/intel_backlight"

max_brightness=$((208))
curr_brightness=$(( $(cat $BRIGHTNESS_PATH/brightness) ))

perc=$(( $curr_brightness * 100 / $max_brightness ))

echo "☀ $perc%"

