#!/bin/bash

muted="OFF"
unmuted='\U1F399'

state=$( amixer get Capture | grep -om1 "\[[onf]*\]" )

if [[ $state == "[on]" ]]; then
    icon=$unmuted
elif [[ $state == "[off]" ]]; then
    icon=$muted
fi

echo -e $icon

