#!/bin/bash

icon='\uF09E'
yellow='#efcd23'

new_feeds=$(( $(newsboat -x print-unread | cut -d ' ' -f1) ))

if [[ $new_feeds -gt 0 ]]; then
    color=$yellow
fi

echo -e "$new_feeds $icon"
echo ''
echo $color
