#!/bin/bash

if [[ $1 == '' ]]; then
    echo "Select one with m and exit with q"
    wp=$(sxiv -ot $HOME/Wallpapers/*)
else
    wp=$1
fi

if [[ -f $wp ]]; then
    wallpaper_dir="$HOME/Wallpapers/"
    wallpaper_name=".current_wallpaper."
    extension=$(basename $wp | cut -d '.' -f2)
    rm "$wallpaper_dir$wallpaper_name"* 2>/dev/null
    cp $wp "$wallpaper_dir$wallpaper_name$extension"
    feh --bg-scale "$wallpaper_dir$wallpaper_name$extension"
    notify-send 'Info' 'Wallpaper set'
else
    echo "No such file"
fi

