#!/bin/bash

if ! [[ -x $(command -v sxiv) ]]; then
    echo "sxiv required"
    exit 1
fi
if ! [[ -x $(command -v feh) ]]; then
    echo "feh required"
    exit 1
fi

if [[ $1 == '' ]]; then
    echo "Select image with m and exit with q"
    wp=$(sxiv -bfot $HOME/Wallpapers/*)
elif [[ $1 == '-s' ]]; then
    if ! [[ $2 == '' ]]; then
        wp=$(sxiv -bfot $HOME/Wallpapers/*$2*)
    fi
else
    wp=$1
fi

if [[ -f $wp ]]; then
    wallpaper_dir="$HOME/Wallpapers/"
    extension=$(basename $wp | cut -d '.' -f2)
    rm "$wallpaper_dir.current_wallpaper."* 2>/dev/null
    cp $wp "$wallpaper_dir.current_wallpaper.$extension"
    feh --bg-scale "$wallpaper_dir.current_wallpaper.$extension"
else
    echo "File not found"
fi

