#!/bin/bash

focused_id=$(xprop -id `xdotool getwindowfocus` _NET_WM_PID | cut -d ' ' -f3)
focused_id=$(( $focused_id + 1 ))

place=$(pwdx $focused_id | cut -d ' ' -f2)

if [[ $place == '' ]]; then
    place="$HOME"
fi

urxvt -cd "$place"

