#!/bin/bash

text=$(xclip -o)
if [[ $? -ne 0 ]]; then
    exit 0
fi

open_in_browser(){
    $BROWSER $text
}

search_in_google(){
    $BROWSER "https://www.google.com/search?q=$text"
}

search_in_wiki(){
    $BROWSER "https://en.wikipedia.org/wiki/$text"
}

download_video(){
    cd $HOME/Downloads
    notify-send "Downloading ..."
    youtube-dl $text
    if [[ $? -eq 0 ]]; then
        notify-send "Video downloaded"
    else
        notify-send "Downloading failed"
    fi
}

save_to_download(){
    echo $text >> $HOME/.music_to_download
    notify-send "URL added"
}


action_google='google'
action_url='open_url'
action_wiki='wiki'
action_video='download_video'
action_music='todo_music'

actions=($action_google)

if [[ $text =~ (https?:\/\/)?(www\.)?\w*\.\w*(\/[^\/ ]*)* ]]; then
    actions+=($action_url $action_video $action_music)
else
    actions+=($action_wiki)
fi

action=$(printf "%s\n" "${actions[@]}" | dmenu -p 'Action:')

case $action in
    $action_google)
        search_in_google
        ;;
    $action_wiki)
        search_in_wiki
        ;;
    $action_url)
        open_in_browser
        ;;
    $action_video)
        download_video
        ;;
    $action_music)
        download_music
        ;;
esac
