#!/bin/bash

text=$(xclip -o -selection clipboard)
actions=('google')

if [[ $text =~ (https?://)?(www\.)?\w*\.\w* ]]; then
    actions+=('open url')
fi

action=$(printf "%s\n" "${actions[@]}" | dmenu)

case $action in
    'google')
        $BROWSER "https://www.google.com/search?q=${text// /\+}" >/dev/null 2>&1 &
        ;;
    'open url')
        $BROWSER $text
        ;;
esac
